/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewsPackage;

public class App {
    public static void main(String[] args) {

        /*
         * Calling Chapter 1 Object
         */
        Ch1ArraysStrings chapter1 = new Ch1ArraysStrings();
        System.out.println(chapter1.toString());
    }


}
